### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

**Creating Numpy Arrays**

In [2]:
# As numpy is library we need to import it.

import numpy as np

np.array([1,2,3])
# can be stored in variable
a = np.array([1,2,3])   # this is a 1D array --> Vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
#2D array

b = np.array([[1,2,3],[4,5,6]])  # 2D array --> Matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
# 3D array (No restriction for creating any number of dimension)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #3D array --> Tenser
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# We can make any data type ka np array
# Syntax --> dtype 
# default is float

np.array([1,2,3],dtype = float)
np.array([1,2,3],dtype = bool)
np.array([1,2,3],dtype = complex)
#np.array([1,2,3],dtype = str)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
# np.arange
np.arange(1,11,2) # first include second exclude(exactly as range)

array([1, 3, 5, 7, 9])

In [26]:
# with reshape

np.arange(1,13).reshape(3,4) # changes into rows and columns (both number product should be equal to range)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# np.ones and np.zeros
np.ones((3,4)) # creates every item as 1 # needs a tuple and the shape
# Use --> to initialize arrays

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random((3,4)) # 0 se 1 ke beech mein random number
# random is class method name is also random

array([[0.75802227, 0.61846867, 0.66392524, 0.697492  ],
       [0.51435451, 0.49738546, 0.95510109, 0.54738306],
       [0.71967813, 0.68007163, 0.10303519, 0.97782671]])

In [8]:
# np.linspace --> linear space 
# 1. lower range -- 2. upper range -- 3. number of items
# generates points at equal distance

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
#np.identity
# creating identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attribute**

In [3]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [5]:
# ndim  ---> Tells the dimension of array
a3.ndim

3

In [8]:
# shape --> tells rows and coloumns
print(a3.shape) # first number kitne 2D array hai then rows and coloumns
a3 

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
# size
a3.size

8

In [15]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)


4
8


In [13]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


**Changing Datatype**

In [19]:
# astype
print(a3.dtype)
a3.astype(np.int64)

int32


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

**Array Operations**

In [32]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [21]:
# Scalar Operation --> ek number se Operate karna

# Arithmetic --> all operator works
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [25]:
# Relation operator --> All relational Operator
a2 > 17  # itemwise comparison

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
# Vector operation --> Using on 2 numpy arrays

# Arithmetic & Relational -- All operations

a1 + a2 # since shape is same itemwise it is added (shape not same -- error)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**Array Functions**

In [38]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100) 
a1

array([[29., 77., 28.],
       [86., 79., 76.],
       [69., 46., 80.]])

In [40]:
# max/min/sum/prod
# 0 -- coloumn & 1-- row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
print(np.max(a1,axis=1))

86.0
28.0
570.0
8197525921643520.0
[77. 86. 80.]


In [41]:
# mean/median/std/var

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))
print(np.median(a1,axis=1))

63.333333333333336
76.0
21.457969252574774
460.44444444444446
[29. 79. 69.]


In [42]:
# trignometric function

np.sin(a1)

array([[-0.66363388,  0.99952016,  0.27090579],
       [-0.92345845, -0.44411267,  0.56610764],
       [-0.11478481,  0.90178835, -0.99388865]])

In [43]:
# dot product --> first column == second row

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [44]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [46]:
# log and exponential

print(np.log(a1))
print(np.exp(a1))

[[3.36729583 4.34380542 3.33220451]
 [4.4543473  4.36944785 4.33073334]
 [4.2341065  3.8286414  4.38202663]]
[[3.93133430e+12 2.75851345e+33 1.44625706e+12]
 [2.23524660e+37 2.03828107e+34 1.01480039e+33]
 [9.25378173e+29 9.49611942e+19 5.54062238e+34]]


In [51]:
# round/floor/ceil

print(np.round(np.arange(10)))
print(np.floor(np.arange(10)))
print(np.ceil(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**Indexing and Slicing**

In [53]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)



In [57]:
# Indexing

print(a1)
a1[-1]

[0 1 2 3 4 5 6 7 8 9]


9

In [59]:
# 2D array

print(a2) 
a2[1,2] # row and column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6

In [60]:
# 3D array

print(a3)
a3[1,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


5

In [61]:
# Slicing

print(a1)
a1[::2]

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [69]:
# 2D array

print(a2)
print(a2[0,:]) # only row
print(a2[:,2]) # only coloumn
print(a2[1:,1:3])
print(a2[::2,::3])
print(a2[::2,1::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]


In [73]:
# 3D array

a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [74]:
print(a3[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [75]:
print(a3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [76]:
print(a3[0,1,:])

[3 4 5]


In [78]:
print(a3[1,1:,::2])

[[12 14]
 [15 17]]


In [79]:
# In above slicing
# First number is for accessing the 2D array
# Second number is for operating on the row of 2D array
# Third number is for operating on the coloumn of 2D array

**Iterating**

In [83]:
for i in (a1):
    print(i)
print(a1)

0
1
2
3
4
5
6
7
8
9
[0 1 2 3 4 5 6 7 8 9]


In [85]:
# 2D array --> 1 row is printed every time
for i in (a2):
    print(i)
print(a2)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [86]:
# 3D array --> 2d array is printed
for i in (a3):
    print(i)
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [87]:
# for individual items

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping**

In [ ]:
# Reshape

a2 = np.arange(10,40).reshape(5,6)
a2

In [101]:
# Transpose  # Temporary
np.transpose(a2)
a2.T # better syntax

array([[10, 16, 22, 28, 34],
       [11, 17, 23, 29, 35],
       [12, 18, 24, 30, 36],
       [13, 19, 25, 31, 37],
       [14, 20, 26, 32, 38],
       [15, 21, 27, 33, 39]])

In [102]:
# ravel --> any dimension array converted into 1D array
# Temporary
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [112]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [113]:
# Horizontal Stacking (joining two numpy arrays) # permanent # size same

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [111]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [114]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [119]:
# Horizontal Stacking (spliting two numpy arrays(vertically)) # permanent # size same

np.hsplit(a4,2)  # equal division should be there

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [121]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]