### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

Not Using sorted because it gives the result in list

In [1]:
# Syntax
import numpy as np
a = np.random.randint(1,100,25)
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [13]:
np.sort(a)
np.sort(a)[::-1] # for reversing

array([99, 98, 98, 94, 94, 90, 83, 78, 77, 71, 71, 67, 66, 64, 63, 61, 53,
       34, 34, 33, 30, 28, 15, 13,  7])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[35, 98, 17, 33],
       [68, 18,  3, 49],
       [68, 57, 68, 73],
       [ 7,  1, 85, 74],
       [23, 34, 83, 16],
       [41, 39, 26, 15]])

In [10]:
np.sort(b) # sorting done through row-wise
np.sort(b,axis = 0) # coloumn wise sort

array([[ 7,  1,  3, 15],
       [23, 18, 17, 16],
       [35, 34, 26, 33],
       [41, 39, 68, 49],
       [68, 57, 83, 73],
       [68, 98, 85, 74]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [14]:
# Syntax
np.append(a,200) # last mein append

array([ 61,  99,  63,  53,  98,  71,  67,  94,   7,  94,  90,  71,  13,
        98,  33,  34,  64,  34,  78,  77,  83,  66,  30,  15,  28, 200])

In [18]:
# 2D array
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[35., 98., 17., 33.,  1.],
       [68., 18.,  3., 49.,  1.],
       [68., 57., 68., 73.,  1.],
       [ 7.,  1., 85., 74.,  1.],
       [23., 34., 83., 16.,  1.],
       [41., 39., 26., 15.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [33]:
# Syntax
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3) # shape should be same

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [32]:
np.concatenate((c,d)) # default coloumn wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [34]:
# Syntax
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [35]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [36]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [39]:
np.expand_dims(a,axis = 0)

array([[61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34,
        64, 34, 78, 77, 83, 66, 30, 15, 28]])

In [40]:
np.expand_dims(a,axis = 0).shape

(1, 25)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [41]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [49]:
# find all indices with value greater than 50 
np.where(a>50) # we are getting all the value of index

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 13, 16, 18, 19, 20, 21],
       dtype=int64),)

In [51]:
# replace all values > 50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

# If condition is true then value which is given at true we execute else it remains unchanged

array([ 0,  0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0, 13,  0, 33, 34,  0,
       34,  0,  0,  0,  0, 30, 15, 28])

In [52]:
np.where(a%2 == 0,0,a)

array([61, 99, 63, 53,  0, 71, 67,  0,  7,  0,  0, 71, 13,  0, 33,  0,  0,
        0,  0, 77, 83,  0,  0, 15,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [53]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [55]:
np.argmax(a) # tells at which the maxmium value is at

1

In [57]:
b

array([[35, 98, 17, 33],
       [68, 18,  3, 49],
       [68, 57, 68, 73],
       [ 7,  1, 85, 74],
       [23, 34, 83, 16],
       [41, 39, 26, 15]])

In [63]:
np.argmax(b,axis = 0) # column wise

array([1, 0, 3, 3], dtype=int64)

In [64]:
# For MINIMUM VALUE

np.argmin(a)

8

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.htmlhtml

In [65]:
# cumsum ---> Cumulative Sum
# To sum of all the number
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [66]:
np.cumsum(a)

array([  61,  160,  223,  276,  374,  445,  512,  606,  613,  707,  797,
        868,  881,  979, 1012, 1046, 1110, 1144, 1222, 1299, 1382, 1448,
       1478, 1493, 1521])

In [67]:
b

array([[35, 98, 17, 33],
       [68, 18,  3, 49],
       [68, 57, 68, 73],
       [ 7,  1, 85, 74],
       [23, 34, 83, 16],
       [41, 39, 26, 15]])

In [69]:
np.cumsum(b,axis = 1) # row - wise

array([[ 35, 133, 150, 183],
       [ 68,  86,  89, 138],
       [ 68, 125, 193, 266],
       [  7,   8,  93, 167],
       [ 23,  57, 140, 156],
       [ 41,  80, 106, 121]])

In [70]:
# For product
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [72]:
np.cumprod(a)

# giving negative number even though it is positive list because dtype = int64 cannot hold that many value then it changes the value

array([         61,        6039,      380457,    20164221,  1976093658,
       -1431271050, -1405879838,   991281404, -1650964764,  -571865160,
          71743152,   798796496,  1794419856,  -240513248,   652997408,
         727075392,  -711815168,  1568088064,  2051784704,  -926367744,
         420888576,  2008842240,   135725056,  2035875840,  1169948672])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [74]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [75]:
np.percentile(a,100)

99.0

In [76]:
np.percentile(a,50)

66.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [78]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [79]:
np.histogram(a)

(array([3, 0, 5, 0, 0, 2, 6, 2, 1, 6], dtype=int64),
 array([ 7. , 16.2, 25.4, 34.6, 43.8, 53. , 62.2, 71.4, 80.6, 89.8, 99. ]))

In [82]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 4, 0, 1, 5, 4, 1, 6], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [86]:
# Syntax
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [84]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [89]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items) # searching multiple item

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False])

In [90]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)] # searching multiple item

array([90, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [91]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [92]:
np.flip(a)

array([28, 15, 30, 66, 83, 77, 78, 34, 64, 34, 33, 98, 13, 71, 90, 94,  7,
       94, 67, 71, 98, 53, 63, 99, 61])

In [95]:
# 2D array
b

array([[35, 98, 17, 33],
       [68, 18,  3, 49],
       [68, 57, 68, 73],
       [ 7,  1, 85, 74],
       [23, 34, 83, 16],
       [41, 39, 26, 15]])

In [96]:
np.flip(b,axis = 1)

array([[33, 17, 98, 35],
       [49,  3, 18, 68],
       [73, 68, 57, 68],
       [74, 85,  1,  7],
       [16, 83, 34, 23],
       [15, 26, 39, 41]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [98]:
# Syntax
a

array([61, 99, 63, 53, 98, 71, 67, 94,  7, 94, 90, 71, 13, 98, 33, 34, 64,
       34, 78, 77, 83, 66, 30, 15, 28])

In [110]:
np.put(a,[0,1],[110,530]) # index & items & changing is also allowed

In [100]:
a

array([110, 530,  63,  53,  98,  71,  67,  94,   7,  94,  90,  71,  13,
        98,  33,  34,  64,  34,  78,  77,  83,  66,  30,  15,  28])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [102]:
# Syntax
a

array([110, 530,  63,  53,  98,  71,  67,  94,   7,  94,  90,  71,  13,
        98,  33,  34,  64,  34,  78,  77,  83,  66,  30,  15,  28])

In [103]:
np.delete(a,[0,2,4])

array([530,  53,  71,  67,  94,   7,  94,  90,  71,  13,  98,  33,  34,
        64,  34,  78,  77,  83,  66,  30,  15,  28])

In [111]:
b

array([[35, 98, 17, 33],
       [68, 18,  3, 49],
       [68, 57, 68, 73],
       [ 7,  1, 85, 74],
       [23, 34, 83, 16],
       [41, 39, 26, 15]])

In [119]:
np.delete(b,[0],axis = 1)

array([[98, 17, 33],
       [18,  3, 49],
       [57, 68, 73],
       [ 1, 85, 74],
       [34, 83, 16],
       [39, 26, 15]])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1dp.in1d

In [104]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [122]:
np.intersect1d(m,n) # prints common

array([3, 4, 5])

In [121]:
np.setdiff1d(n,m) # printing the value which the other set is missing

array([6, 7])

In [120]:
np.setxor1d(m,n) # removing common

array([1, 2, 6, 7])

In [124]:
np.in1d(m,2) # Checks if value is given or not

array([False,  True, False, False, False])

In [126]:
m[np.in1d(m,2)]

array([2])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [127]:
# Syntax
a

array([110, 530,  63,  53,  98,  71,  67,  94,   7,  94,  90,  71,  13,
        98,  33,  34,  64,  34,  78,  77,  83,  66,  30,  15,  28])

In [130]:
np.clip(a,a_min = 25, a_max = 75) # changing the value in certain range

array([75, 75, 63, 53, 75, 71, 67, 75, 25, 75, 75, 71, 25, 75, 33, 34, 64,
       34, 75, 75, 75, 66, 30, 25, 28])